/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3ENEXTPEER_AUTODEFS_H
#define S3ENEXTPEER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_NEXTPEER_NAME "s3eNextpeer"
#define S3E_EXT_NEXTPEER_HASH 0x9aa36f5b

#endif /* !S3ENEXTPEER_AUTODEFS_H */
